apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-demo-deployment
  labels:
    app: node-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-demo
  template:
    metadata:
      labels:
        app: node-demo
    spec:
      containers:
      - name: node-demo
        image: docrob1337/node-demo:latest
        ports:
        - containerPort: 3000
